### ISSUE TITLE
Issue during printing an HTML Field

### ISSUE THREAD

**Issue by rjay1018** [JayVora-SerpentCS/Jasperv8#116]
![image](https://user-images.githubusercontent.com/5526244/95604960-df1e4680-0a8a-11eb-8b69-ed7a845414d0.png)

**Comment by JayVora-SerpentCS** [comment]
@hiren-serpentcs take a look please.

**Comment by h3llopy** [comment]
Same Error

**Comment by hiren-serpentcs** [comment]
Hi @rjay1018 

Looking at the log, it's because the jasper server is not able to load the custom fonts.

You can try to add your custom font's jar files into the java folder.

**Comment by rjay1018** [comment]
@hiren-serpentcs where can I find the Java folder?

**Comment by hiren-serpentcs** [comment]
Hi @rjay1018 

You need to add your jar file in this directory: `jasper_reports/java/lib`

**Comment by rjay1018** [comment]
Do I need to create a jar file? I only use have this HTML Field on my system. .

![image](https://user-images.githubusercontent.com/5526244/97019575-0c86ec00-1583-11eb-8bc1-36b04e3ce0b2.png)

I set it on ireport as markup = html

![image](https://user-images.githubusercontent.com/5526244/97019684-3213f580-1583-11eb-87ce-6e7ee7dde4cb.png)

I did not create a jar file or any, Do you have any reference documents that will guide me resolved this issue.

**Comment by hiren-serpentcs** [comment]
> Do I need to create a jar file?

Yes since your HTML is taking the "Arial Narrow" which is not available/rendered on the Jasper Server.

You can refer to [this doc](https://community.jaspersoft.com/documentation/tibco-jaspersoft-studio-user-guide/v640/working-font-extensions#:~:text=In%20Window%20%3E%20Preferences%20%3E%20Jaspersoft%20Studio,Amaranth%2C%20Lobster%2C%20and%20SampleFontSet.&text=In%20the%20Export%20Font%20to,exported%20file%20and%20click%20Save.) to create your own jar file for Fonts.

**Comment by hiren-serpentcs** [comment]
closing as no updates.
